### ISSUE TITLE
Cannot Download the Dataset!

### ISSUE THREAD

**Issue by sard0r** [vturrisi/CO2A#2]
Hello I am sorry to say that I have tried over 10 times to download the Mixamo dataset. I wanted to observe it for research purposes. But after going up to 38gb the download is breaking. I do not have the read access to the dataset. If possible can you share the dataset in chunks or give read access to mailssardor@gmail.com?

Thank you very much!

**Comment by vturrisi** [comment]
Hey,

Everyone with the link can view/read the file by default. It seems that you are just getting disconnected (hence why you can download part of the file) but I'll check again if I can download it from my side just in case.

About dividing the dataset in chunks, I can eventually do it, but I'm pretty busy at the moment, so it might take some time.

**Comment by sard0r** [comment]
Thank you very much for your kind reply. 

Every time when I reach the same point download is crashing.

![image](https://user-images.githubusercontent.com/61651742/185471876-e3f2c830-3a2d-4051-8dd3-6eb8a21f007f.png)

**Comment by zgzxy001** [comment]
I'm not able to download it as well. Could you upload the dataset in chunks? Thanks!

**Comment by vturrisi** [comment]
Hi,
I understand that the file might be too large to download with an unstable network, but try to use **gdown** to download the file. On our side, we will try do divide it into smallers chunks to facilitate with that and try to upload in the next week or so.
