### ISSUE TITLE
About source domain when transfer from 'Kinetics' to 'NEC-Drone'

### ISSUE THREAD

**Issue by zhenweibao** [vturrisi/CO2A#4]
Hi, thinks for your contribution in this work.
      I am not sure about which source date to use when dong this transfer.  Do you use all the training and testing data (which corresponding to NEC-Drone) in Kinetics dataset?
      If possible, could you please upload the training list (just for Kinetics) ?

**Comment by vturrisi** [comment]
Hi,
We used the Kinetics classes following the [NEC-Drone original paper](https://openaccess.thecvf.com/content_WACV_2020/papers/Choi_Unsupervised_and_Semi-Supervised_Domain_Adaptation_for_Action_Recognition_from_Drones_WACV_2020_paper.pdf). You can find the respective class relation between the two datasets in their [supplementary material](https://openaccess.thecvf.com/content_WACV_2020/supplemental/Choi_Unsupervised_and_Semi-Supervised_WACV_2020_supplemental.pdf).

![image](https://user-images.githubusercontent.com/34046216/200817478-c7ed76ec-3502-413b-9f58-ef62ac073227.png)
