### ISSUE TITLE
Filelist request

### ISSUE THREAD

**Issue by Backdrop9019** [vturrisi/CO2A#5]
Hello, thank you for your great research.
I would like to know the train and val file lists for the kinetics-nec_drone dataset you used in your experiment.
Where can I obtain them?

**Comment by vturrisi** [comment]
You can directly download the nec-drone dataset from the original paper https://www.nec-labs.com/~mas/NEC-Drone.

**Comment by Backdrop9019** [comment]
The NEC drone only provides a filelist for the drone dataset. How did you create the filelist for Kinetics?

**Comment by vturrisi** [comment]
You will need to match the classes of NEC drone with kinetics and then download them following the way described in the kinetics repo.
